'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class orde
    Public Property id As Integer
    Public Property customer_name As String
    Public Property customer_email As String
    Public Property customer_mobil As String
    Public Property status As String
    Public Property create_at As Nullable(Of Date)
    Public Property upadte_at As Nullable(Of Date)

End Class
